"""Auto-categorization of tools based on name and description."""

import re
from devflow.tools.models import ToolBrowserCategory


class ToolCategorizer:
    """Categorizes tools based on name and description keywords."""

    # Keywords for auto-categorization (checked against name and description)
    CATEGORY_KEYWORDS: dict[ToolBrowserCategory, list[str]] = {
        ToolBrowserCategory.LANGUAGES: [
            "node",
            "nodejs",
            "python",
            "ruby",
            "rust",
            "rustc",
            "cargo",
            "go",
            "golang",
            "java",
            "jdk",
            "jre",
            "openjdk",
            "php",
            "swift",
            "kotlin",
            "scala",
            "elixir",
            "erlang",
            "lua",
            "perl",
            "r-lang",
            "julia",
            "nim",
            "zig",
            "crystal",
            "dart",
            "flutter",
            "deno",
            "bun",
            "dotnet",
            ".net",
            "csharp",
            "fsharp",
            "haskell",
            "ocaml",
            "clojure",
            "groovy",
            "typescript",
            "runtime",
            "interpreter",
            "compiler",
            "language server",
            "lsp",
            "pyenv",
            "rbenv",
            "nvm",
            "sdkman",
            "asdf",
            "mise",
            "volta",
            "fnm",
        ],
        ToolBrowserCategory.DATABASES: [
            "postgres",
            "postgresql",
            "mysql",
            "mariadb",
            "sqlite",
            "redis",
            "mongo",
            "mongodb",
            "database",
            "cassandra",
            "elasticsearch",
            "elastic",
            "cockroach",
            "clickhouse",
            "influx",
            "timescale",
            "neo4j",
            "graph database",
            "sql",
            "nosql",
            "dynamodb",
            "fauna",
            "supabase",
            "planetscale",
            "dbeaver",
            "datagrip",
            "sequel",
            "tableplus",
            "pgadmin",
            "phpmyadmin",
            "adminer",
            "prisma",
            "drizzle",
        ],
        ToolBrowserCategory.CONTAINERS: [
            "docker",
            "podman",
            "colima",
            "container",
            "kubernetes",
            "k8s",
            "k3s",
            "k3d",
            "minikube",
            "kind",
            "rancher",
            "lima",
            "vagrant",
            "virtualbox",
            "vmware",
            "parallels",
            "qemu",
            "multipass",
            "utm",
            "orbstack",
            "finch",
            "nerdctl",
            "containerd",
            "buildah",
            "skopeo",
        ],
        ToolBrowserCategory.CLOUD: [
            "aws",
            "amazon",
            "gcloud",
            "google cloud",
            "azure",
            "terraform",
            "pulumi",
            "cloudformation",
            "cdk",
            "serverless",
            "lambda",
            "vercel",
            "netlify",
            "railway",
            "render",
            "fly.io",
            "flyctl",
            "heroku",
            "digitalocean",
            "doctl",
            "linode",
            "vultr",
            "cloudflare",
            "wrangler",
            "infrastructure",
            "iac",
            "openstack",
            "opentofu",
        ],
        ToolBrowserCategory.VERSION_CONTROL: [
            "git",
            "github",
            "gitlab",
            "bitbucket",
            "mercurial",
            "hg",
            "svn",
            "subversion",
            "version control",
            "vcs",
            "gh",
            "hub",
            "glab",
            "lazygit",
            "tig",
            "gitui",
            "sourcetree",
            "fork",
            "gitkraken",
            "tower",
            "sublime merge",
            "diff",
            "merge",
            "delta",
            "difftastic",
        ],
        ToolBrowserCategory.EDITORS: [
            "vscode",
            "visual studio",
            "neovim",
            "nvim",
            "vim",
            "emacs",
            "sublime",
            "atom",
            "notepad",
            "textmate",
            "bbedit",
            "coteditor",
            "zed",
            "helix",
            "kakoune",
            "nano",
            "micro",
            "editor",
            "ide",
            "intellij",
            "pycharm",
            "webstorm",
            "goland",
            "rubymine",
            "phpstorm",
            "rider",
            "clion",
            "android studio",
            "xcode",
            "cursor",
            "lapce",
            "nova",
        ],
        ToolBrowserCategory.SHELL: [
            "zsh",
            "bash",
            "fish",
            "shell",
            "terminal",
            "tmux",
            "screen",
            "zellij",
            "starship",
            "oh-my-zsh",
            "powerlevel",
            "iterm",
            "alacritty",
            "kitty",
            "wezterm",
            "warp",
            "hyper",
            "tabby",
            "rio",
            "ghostty",
            "prompt",
            "readline",
            "fzf",
            "atuin",
            "mcfly",
            "zoxide",
            "autojump",
            "nushell",
            "elvish",
            "xonsh",
        ],
        ToolBrowserCategory.BUILD_TOOLS: [
            "make",
            "cmake",
            "ninja",
            "gradle",
            "maven",
            "ant",
            "bazel",
            "buck",
            "meson",
            "scons",
            "build",
            "webpack",
            "vite",
            "esbuild",
            "rollup",
            "parcel",
            "turbo",
            "nx",
            "lerna",
            "pnpm",
            "yarn",
            "npm",
            "bundler",
            "pip",
            "poetry",
            "pdm",
            "uv",
            "rye",
            "hatch",
            "setuptools",
            "task",
            "just",
            "earthly",
            "pants",
        ],
        ToolBrowserCategory.SECURITY: [
            "gpg",
            "gnupg",
            "age",
            "sops",
            "vault",
            "1password",
            "bitwarden",
            "lastpass",
            "keychain",
            "ssh",
            "openssh",
            "openssl",
            "tls",
            "ssl",
            "certificate",
            "mkcert",
            "cert",
            "security",
            "encrypt",
            "decrypt",
            "password",
            "secret",
            "credential",
            "cosign",
            "sigstore",
            "trivy",
            "snyk",
            "grype",
            "syft",
            "checkov",
            "tfsec",
            "semgrep",
            "bandit",
            "brakeman",
        ],
        ToolBrowserCategory.NETWORKING: [
            "curl",
            "wget",
            "httpie",
            "http",
            "ngrok",
            "cloudflared",
            "tunnel",
            "proxy",
            "nginx",
            "caddy",
            "traefik",
            "haproxy",
            "envoy",
            "network",
            "dns",
            "dig",
            "nslookup",
            "ping",
            "traceroute",
            "mtr",
            "netcat",
            "nmap",
            "wireshark",
            "tcpdump",
            "postman",
            "insomnia",
            "hoppscotch",
            "paw",
            "grpcurl",
            "websocat",
            "socat",
        ],
        ToolBrowserCategory.MEDIA: [
            "ffmpeg",
            "imagemagick",
            "gimp",
            "inkscape",
            "blender",
            "obs",
            "vlc",
            "mpv",
            "handbrake",
            "audacity",
            "lmms",
            "krita",
            "darktable",
            "rawtherapee",
            "figma",
            "sketch",
            "pixelmator",
            "affinity",
            "photoshop",
            "illustrator",
            "video",
            "audio",
            "image",
            "photo",
            "graphics",
            "media",
            "convert",
            "resize",
            "compress",
            "encode",
            "decode",
            "transcode",
            "exiftool",
            "yt-dlp",
            "youtube-dl",
        ],
        ToolBrowserCategory.PRODUCTIVITY: [
            "ripgrep",
            "rg",
            "ag",
            "ack",
            "fd",
            "find",
            "grep",
            "sed",
            "awk",
            "jq",
            "yq",
            "xq",
            "bat",
            "cat",
            "less",
            "more",
            "exa",
            "eza",
            "lsd",
            "tree",
            "dust",
            "duf",
            "ncdu",
            "htop",
            "btop",
            "top",
            "procs",
            "bottom",
            "glances",
            "noti",
            "watch",
            "entr",
            "direnv",
            "dotenv",
            "tldr",
            "cheat",
            "hyperfine",
            "tokei",
            "cloc",
            "scc",
            "glow",
            "mdcat",
        ],
        ToolBrowserCategory.DEVOPS: [
            "ansible",
            "chef",
            "puppet",
            "salt",
            "helm",
            "kustomize",
            "argocd",
            "flux",
            "jenkins",
            "circleci",
            "travis",
            "github actions",
            "gitlab ci",
            "drone",
            "tekton",
            "spinnaker",
            "prometheus",
            "grafana",
            "datadog",
            "newrelic",
            "sentry",
            "pagerduty",
            "opsgenie",
            "loki",
            "jaeger",
            "zipkin",
            "opentelemetry",
            "otel",
            "logstash",
            "fluentd",
            "vector",
            "kubectl",
            "k9s",
            "lens",
            "octant",
            "stern",
            "kubectx",
            "eksctl",
            "gke",
            "aks",
        ],
        ToolBrowserCategory.APPLICATIONS: [
            # GUI apps are auto-categorized from casks, but these keywords help
            "browser",
            "chrome",
            "firefox",
            "safari",
            "brave",
            "arc",
            "edge",
            "opera",
            "vivaldi",
            "slack",
            "discord",
            "zoom",
            "teams",
            "skype",
            "telegram",
            "signal",
            "whatsapp",
            "messenger",
            "notion",
            "obsidian",
            "roam",
            "logseq",
            "bear",
            "craft",
            "ulysses",
            "iawriter",
            "typora",
            "spotify",
            "apple music",
            "tidal",
        ],
    }

    # Exact name matches take priority (lowercase)
    EXACT_MATCHES: dict[str, ToolBrowserCategory] = {
        # Languages
        "node": ToolBrowserCategory.LANGUAGES,
        "nodejs": ToolBrowserCategory.LANGUAGES,
        "python": ToolBrowserCategory.LANGUAGES,
        "python3": ToolBrowserCategory.LANGUAGES,
        "ruby": ToolBrowserCategory.LANGUAGES,
        "rust": ToolBrowserCategory.LANGUAGES,
        "go": ToolBrowserCategory.LANGUAGES,
        "java": ToolBrowserCategory.LANGUAGES,
        "php": ToolBrowserCategory.LANGUAGES,
        "swift": ToolBrowserCategory.LANGUAGES,
        "kotlin": ToolBrowserCategory.LANGUAGES,
        "scala": ToolBrowserCategory.LANGUAGES,
        "elixir": ToolBrowserCategory.LANGUAGES,
        "erlang": ToolBrowserCategory.LANGUAGES,
        "lua": ToolBrowserCategory.LANGUAGES,
        "perl": ToolBrowserCategory.LANGUAGES,
        "r": ToolBrowserCategory.LANGUAGES,
        "julia": ToolBrowserCategory.LANGUAGES,
        "nim": ToolBrowserCategory.LANGUAGES,
        "zig": ToolBrowserCategory.LANGUAGES,
        "crystal": ToolBrowserCategory.LANGUAGES,
        "dart": ToolBrowserCategory.LANGUAGES,
        "deno": ToolBrowserCategory.LANGUAGES,
        "bun": ToolBrowserCategory.LANGUAGES,
        # Databases
        "postgres": ToolBrowserCategory.DATABASES,
        "postgresql": ToolBrowserCategory.DATABASES,
        "mysql": ToolBrowserCategory.DATABASES,
        "redis": ToolBrowserCategory.DATABASES,
        "mongodb": ToolBrowserCategory.DATABASES,
        "sqlite": ToolBrowserCategory.DATABASES,
        # Containers
        "docker": ToolBrowserCategory.CONTAINERS,
        "podman": ToolBrowserCategory.CONTAINERS,
        "colima": ToolBrowserCategory.CONTAINERS,
        "kubectl": ToolBrowserCategory.DEVOPS,
        "helm": ToolBrowserCategory.DEVOPS,
        # Cloud
        "aws": ToolBrowserCategory.CLOUD,
        "gcloud": ToolBrowserCategory.CLOUD,
        "azure": ToolBrowserCategory.CLOUD,
        "terraform": ToolBrowserCategory.CLOUD,
        # VCS
        "git": ToolBrowserCategory.VERSION_CONTROL,
        "gh": ToolBrowserCategory.VERSION_CONTROL,
        "hub": ToolBrowserCategory.VERSION_CONTROL,
        # Editors
        "vim": ToolBrowserCategory.EDITORS,
        "neovim": ToolBrowserCategory.EDITORS,
        "emacs": ToolBrowserCategory.EDITORS,
        # Shell
        "zsh": ToolBrowserCategory.SHELL,
        "bash": ToolBrowserCategory.SHELL,
        "fish": ToolBrowserCategory.SHELL,
        "tmux": ToolBrowserCategory.SHELL,
        "fzf": ToolBrowserCategory.SHELL,
        # Build tools
        "make": ToolBrowserCategory.BUILD_TOOLS,
        "cmake": ToolBrowserCategory.BUILD_TOOLS,
        "npm": ToolBrowserCategory.BUILD_TOOLS,
        "yarn": ToolBrowserCategory.BUILD_TOOLS,
        "pnpm": ToolBrowserCategory.BUILD_TOOLS,
        # Productivity
        "ripgrep": ToolBrowserCategory.PRODUCTIVITY,
        "rg": ToolBrowserCategory.PRODUCTIVITY,
        "fd": ToolBrowserCategory.PRODUCTIVITY,
        "jq": ToolBrowserCategory.PRODUCTIVITY,
        "bat": ToolBrowserCategory.PRODUCTIVITY,
        "eza": ToolBrowserCategory.PRODUCTIVITY,
        "exa": ToolBrowserCategory.PRODUCTIVITY,
        # Networking
        "curl": ToolBrowserCategory.NETWORKING,
        "wget": ToolBrowserCategory.NETWORKING,
        "httpie": ToolBrowserCategory.NETWORKING,
        "ngrok": ToolBrowserCategory.NETWORKING,
    }

    @classmethod
    def categorize(
        cls,
        name: str,
        description: str = "",
        is_cask: bool = False,
    ) -> ToolBrowserCategory:
        """Determine category from tool name and description.

        Args:
            name: Tool name (e.g., "node", "docker-desktop")
            description: Tool description
            is_cask: Whether this is a Homebrew cask (GUI app)

        Returns:
            The most appropriate category for the tool.
        """
        name_lower = name.lower()

        # Check exact name matches first
        if name_lower in cls.EXACT_MATCHES:
            return cls.EXACT_MATCHES[name_lower]

        # Combine name and description for keyword matching
        text = f"{name_lower} {description.lower()}"

        # Score each category based on keyword matches
        scores: dict[ToolBrowserCategory, int] = {}

        for category, keywords in cls.CATEGORY_KEYWORDS.items():
            score = 0
            for keyword in keywords:
                # Exact word match in name gets highest score
                if re.search(rf"\b{re.escape(keyword)}\b", name_lower):
                    score += 10
                # Partial match in name
                elif keyword in name_lower:
                    score += 5
                # Match in description
                elif re.search(rf"\b{re.escape(keyword)}\b", description.lower()):
                    score += 2
                elif keyword in description.lower():
                    score += 1

            if score > 0:
                scores[category] = score

        # Return highest scoring category
        if scores:
            return max(scores, key=lambda c: scores[c])

        # Default: casks are Applications, others are Other
        if is_cask:
            return ToolBrowserCategory.APPLICATIONS

        return ToolBrowserCategory.OTHER
